Update RestCallTests.java
jfrog/artifactory-client-java pull request #300
Opened 2021-01-04 19:06 UTC by idan-marciano-jfrog

Fix testDeleteBuild test

2021-01-04 19:13 UTC, idan-marciano-jfrog commented
I have read the CLA Document and I hereby sign the CLA

2021-01-05 10:19 UTC, yahavi requested changes
Thanks, @idan-marciano-jfrog, looks good!
Please add an empty line between deleteBuild and getBuilds.

2021-01-05 10:19 UTC, yahavi commented on services/src/test/java/org/jfrog/artifactory/client/RestCallTests.java
> +    private String getBuilds() throws Exception {
```suggestion
    }
    
    private String getBuilds() throws Exception {
```

2021-01-05 10:20 UTC, yahavi commented on services/src/test/java/org/jfrog/artifactory/client/RestCallTests.java
> +    private String getBuilds() throws Exception {
```suggestion

    private String getBuilds() throws Exception {
```

2021-01-06 07:32 UTC, merged