Search by file specs
jfrog/artifactory-client-java pull request #323
Opened 2021-06-27 12:55 UTC by asafgabai

- [x] All [tests](https://github.com/jfrog/artifactory-client-java#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
-----

2021-06-27 14:38 UTC, asafgabai commented on build.gradle
> +        compile 'org.jfrog.filespecs:file-specs-java:1.0.x-SNAPSHOT'
Reminder for myself to change it after file-specs-java is released.

2021-06-28 06:46 UTC, eyalbe4 requested changes

2021-06-28 06:46 UTC, eyalbe4 commented on services/src/test/java/org/jfrog/artifactory/client/SearchTests.java
> +            inputStream = this.getClass().getResourceAsStream("/sample.txt");
This input steam needs to be closed after it is used.
The best way to do this, is using "try with resources", they way it is demonstrated in the README:
```
     try (InputStream inputStream = Files.newInputStream(Paths.get("fileToUpload.txt"))) {
         ...
     }
```

2021-06-28 06:46 UTC, eyalbe4 commented on services/src/test/java/org/jfrog/artifactory/client/SearchTests.java
> +        for (int i = 2; i <= 3; i++) {
Let's add a comment above this loop, describing what we're setting up here,

2021-06-28 08:35 UTC, merged