Allow missing contentType
jfrog/artifactory-client-java pull request #332
Opened 2021-11-29 14:54 UTC by yaroslav-orel-jfrog

Fixes https://github.com/jfrog/artifactory-client-java/issues/331

2021-11-29 14:56 UTC, yaroslav-orel-jfrog commented
I have read the CLA Document and I hereby sign the CLA

2021-11-29 14:56 UTC, yaroslav-orel-jfrog commented
recheck

2021-12-23 14:26 UTC, yahavi requested changes

2021-12-23 14:26 UTC, yahavi commented on services/src/main/groovy/org/jfrog/artifactory/client/impl/ArtifactoryImpl.java
> +        if(artifactoryRequest.getRequestType() != null){
```suggestion
        if (artifactoryRequest.getRequestType() != null) {
```

2022-01-04 12:43 UTC, merged