Add support for OCI package type #386
jfrog/artifactory-client-java pull request #387
Opened 2024-07-17 13:19 UTC by jcoste-orange

- [x] All [tests](https://github.com/jfrog/artifactory-client-java#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
-----

2024-07-17 13:20 UTC, jcoste-orange commented
I have read the CLA Document and I hereby sign the CLA

2024-08-20 07:39 UTC, jcoste-orange commented
I don't understand why some tests are failling as they are not related to the pull request.

Did someone has an idea ?

2024-08-30 06:50 UTC, yahavi requested changes
Thanks for your contribution, @jcoste-orange!
Please consider my inline comments.

2024-08-30 06:50 UTC, yahavi commented on services/src/main/java/org/jfrog/artifactory/client/model/repository/settings/impl/OciRepositorySettingsImpl.java
> +    }
Looks unnecessary 
```suggestion
```

2024-08-30 06:50 UTC, yahavi commented on services/src/main/java/org/jfrog/artifactory/client/model/repository/settings/impl/OciRepositorySettingsImpl.java
> +        return true;
Please consider this change:
```suggestion
        if (!(o instanceof OciRepositorySettingsImpl)) {
            return false;
        }
        return super.equals(o);
```

2024-08-30 06:50 UTC, yahavi commented on services/src/main/java/org/jfrog/artifactory/client/model/repository/settings/impl/OciRepositorySettingsImpl.java
> +    }
There is no point in overriding this method
```suggestion
```

2024-09-02 08:53 UTC, jcoste-orange commented
@yahavi I push a new commit to take into account your review.

2024-09-02 09:30 UTC, yahavi approved these changes
Thanks a lot for this, @jcoste-orange!

2024-09-02 09:30 UTC, merged

2024-09-02 09:53 UTC, yahavi commented
@jcoste-orange 
Artifactory Java client version 2.18.0 has been released and is anticipated to be available on Maven Central within a few hours.
Please feel welcome to share your feedback here.

2024-09-10 08:33 UTC, jonesbusy commented
Thanks! I think we miss also the 'helmoci' repo which should be also similar to the "generic" OCI type

2024-10-03 08:14 UTC, yahavi commented
@jonesbusy   
Artifactory Java client version 1.19.0 has been released, featuring your [fix](https://github.com/jfrog/artifactory-client-java/pull/391) for this issue.  
Kindly let us know if that resolved the issue.